### ISSUE TITLE
System.ObjectDisposedException

### ISSUE THREAD

**Issue by huangyedie** [l2999019/GZY.Quartz.MUI#1]
System.ObjectDisposedException:“Cannot access a disposed object.
此异常最初是在此调用堆栈中引发的: 
    [外部代码]

**Comment by l2999019** [comment]
呃 能提供详细的错误信息么?

**Comment by huangyedie** [comment]
我按照流程操作的，我提供一下代码吧。
 var optionsBuilder = new DbContextOptionsBuilder<QuarzEFContext>();
            optionsBuilder.UseMySql("server=xxxx;port=3306;database=yanwentest_hms;uid=xxx;pwd=xxx;sslmode=none", b => b.MaxBatchSize(1));
            services.AddQuartzUI(optionsBuilder.Options);



app.UseQuartz(); //这里注入Quartz

**Comment by huangyedie** [comment]
能提供一个联系方式吗？qq或者微信。我加下你。给你上点图片。你看一下应该就明白了。我的qq或者微信1360651533

**Comment by l2999019** [comment]
采用本地持久化存储 应该能解决这个问题  MYSQL数据库存储 这块我还没写测试,所以可能会有一些问题

**Comment by Run2948** [comment]
解决方案：
```csharp
private QuarzEFContext _quarzEFContext;
        private readonly DbContextOptions<QuarzEFContext> _options;

        public EFQuartzLogService(QuarzEFContext quarzEFContext, DbContextOptions<QuarzEFContext> options)
        {
            _quarzEFContext = quarzEFContext;
            _options = options;
        }

        public async Task<ResultQuartzData> AddLog(tab_quarz_tasklog tab_Quarz_Tasklog)
        {
            using var context = new QuarzEFContext(_options);
            context.tab_quarz_tasklog.Add(tab_Quarz_Tasklog);
            var data = await context.SaveChangesAsync();

            var result = new ResultQuartzData { status = false, message = "" };
            if (data > 0)
            {
                result.status = true;
                result.message = "数据库任务日志添加成功!";
            }
            return result;
        }

```
完整案例可以参考： [EFQuartzLogService.cs](https://github.com/Run2948/QuartzUI.Extension.AspNetCore/blob/main/src/QuartzUI.Extension.AspNetCore/Service/EFQuartzLogService.cs)

**Comment by ganjubing** [comment]
mysql首次运行成功，添加任务后，重启服务重新运行，报错：System.ObjectDisposedException:“Cannot access a disposed object. A common cause of this error is disposing a context that was resolved from dependency injection and then later trying to use the same context instance elsewhere in your application. This may occur if you are calling Dispose() on the context, or wrapping the context in a using statement. If you are using dependency injection, you should let the dependency injection container take care of disposing context instances.
”
把数据表删掉重新运行又可以，是怎么回事呢

**Comment by wdqzdd** [comment]
还维护吗？
