### ISSUE TITLE
使用mysql数据库，在创建了一个调度任务后，再次启动后，System.ObjectDisposedException: Cannot access a disposed context instance

### ISSUE THREAD

**Issue by Jiadm** [l2999019/GZY.Quartz.MUI#11]
NET6
![image](https://user-images.githubusercontent.com/70120480/206060653-75a23c9e-e825-4b37-b934-1e65e51b97dd.png)

![image](https://user-images.githubusercontent.com/70120480/206060766-dbb8e780-df78-4cab-98df-d019553b12c9.png)

**Comment by Jiadm** [comment]
看了下源代码，看上去在启动InitJob的时候，在addlog的方法的时候，上下文被释放了。。。搞不太懂，期待作者帮忙查查；

**Comment by wgq4812** [comment]
的确是有这个bug

**Comment by wgq4812** [comment]
用本地json持久化调度任务,无需数据库   这个不会有问题。但是用数据库的话，会有这个bug

**Comment by l2999019** [comment]
@Jiadm 可以提交合并 修复这个问题

**Comment by Jiadm** [comment]
@l2999019 已提交

**Comment by l2999019** [comment]
> @l2999019 已提交

好的 已合并

**Comment by l2999019** [comment]
@Jiadm OK 测试后下个版本发布到nuget
