### ISSUE TITLE
数据库方式有异常

### ISSUE THREAD

**Issue by hanxiaxuanyuan** [l2999019/GZY.Quartz.MUI#16]
数据库方式可以创建表，但是执行到app.UseQuartz();会报错，提示数据库链接未打开或者已关闭

**Comment by hanxiaxuanyuan** [comment]
使用的是mssql

**Comment by SG-009** [comment]
![image](https://user-images.githubusercontent.com/109298325/236663243-904206c7-351b-4193-8934-4020bbabe97e.png)
Mssql数据库引入不成功是什么原因

**Comment by l2999019** [comment]
这个问题我会验证一下

**Comment by l2999019** [comment]
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/10385855/b1b61432-3a8c-4160-bfd0-e84401a0408b)
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/10385855/8dda5538-8305-4e8a-806b-aa393e0b969b)
我特意开了个Demo测试了一下 未发现你说的问题

**Comment by hanxiaxuanyuan** [comment]
大佬可以把完整的代码发我一份吗，谢谢，非常着急，我不知道哪里出问题了&nbsp;
&nbsp;


11
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年5月17日(星期三) 中午11:45
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [l2999019/GZY.Quartz.MUI] 数据库方式有异常 (Issue #16)





 

 
 我特意开了个Demo测试了一下 未发现你说的问题

**Comment by hanxiaxuanyuan** [comment]
我是再.NET6中使用的，代码如下



报错信息 ：System.InvalidOperationException:“Invalid operation. The connection is closed.”


11
***@***.***





&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l2999019/GZY.Quartz.MUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 中午11:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l2999019/GZY.Quartz.MUI] 数据库方式有异常 (Issue #16)





 

 
 我特意开了个Demo测试了一下 未发现你说的问题

**Comment by l2999019** [comment]
项目完全开源的 所有的代码均在本开源项目里..可以自行下载
你使用的什么版本?
使用最新的2.1版本试试

**Comment by hanxiaxuanyuan** [comment]
我这里怎么都不行，实在是没有办法了


11
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l2999019/GZY.Quartz.MUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 中午1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l2999019/GZY.Quartz.MUI] 数据库方式有异常 (Issue #16)





 
项目完全开源的 所有的代码均在本开源项目里..可以自行下载
 你使用的什么版本?
 使用最新的2.1版本试试

**Comment by hanxiaxuanyuan** [comment]
2.1可以了，谢谢大佬




11
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l2999019/GZY.Quartz.MUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 中午1:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l2999019/GZY.Quartz.MUI] 数据库方式有异常 (Issue #16)





 
项目完全开源的 所有的代码均在本开源项目里..可以自行下载
 你使用的什么版本?
 使用最新的2.1版本试试

**Comment by l2999019** [comment]
issue我关闭了

**Comment by hanxiaxuanyuan** [comment]
好的，感谢

11
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "l2999019/GZY.Quartz.MUI"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 下午2:50
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [l2999019/GZY.Quartz.MUI] 数据库方式有异常 (Issue #16)





 
issue我关闭了
