### ISSUE TITLE
本地化 【Development/Production/Staging】场景支持

### ISSUE THREAD

**Issue by SG-009** [l2999019/GZY.Quartz.MUI#17]
作者你好:
数据库模式可以根据【Development/Production/Staging】不同的场景Use不同的数据库地址
本地化也优化一下根据场景加载不同的 task_job.json 文件

如果Services.AddQuartzUI(); 这里可以开放指定文件名Services.AddQuartzUI("task_job.Development.json"); 将能够适配更多的使用场景

**Comment by l2999019** [comment]
根据环境变量加载不同的数据库 我觉得应该是在应用层面去添加的 也就是你引用这个组件的WebAPI项目去判断和实现的.
而不是在组件中实现的 脱离了组件应该管控的范围

**Comment by SG-009** [comment]
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/109298325/facd8ea0-b53f-4134-9b50-93b7e52ca9f3)
以上是使用数据库模式根据场景切换不同的数据源,由于Sqlserver引入后有错误,所以切换成本地文件模式
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/109298325/b4d09ea2-139d-45ba-9edd-b6087d6fb42d)
是否可以支持这种模式,QuartzSettings文件夹下可以根据指定文件名称生成不同的数据文件,当我们注入时可以自由选择本地化数据文件源

**Comment by l2999019** [comment]
不打算支持这种情况
