### ISSUE TITLE
当我在项目中使用 认证的时候  会导致认证中间件失效

### ISSUE THREAD

**Issue by wangju-net** [l2999019/GZY.Quartz.MUI#18]
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/52590097/364449e2-e203-4b7e-946f-12e1edb684c6)
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/52590097/4b1f5cc3-c576-47dc-88c7-c229578cf7ae)

### **当我不注册中间件时接口正常**
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/52590097/050e39c0-d66c-4eb4-9731-4b8644c54097)
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/52590097/a1341199-baaf-48ea-8520-321fc5703041)
**当我使用时一切正常，需要认证的接口全部报错。**

**Comment by l2999019** [comment]
有没有试过将Quartz方在授权和认证上面

**Comment by q89683495** [comment]
我也是，有没有解决方法呀？？
