### ISSUE TITLE
第二次启动报Invalid attempt to call ReadAsync when reader is closed.

### ISSUE THREAD

**Issue by qiect** [l2999019/GZY.Quartz.MUI#2]
我发现，如果数据库里任务表有数据，那么第二次启动的时候，会抛出这个异常：Invalid attempt to call ReadAsync when reader is closed。
**异常显示是在这行除了问题：**
`var jobs = await _quartzService.GetJobs(p => 1 == 1);`

**转到定义：**
`        public async Task<List<tab_quarz_task>> GetJobs(Expression<Func<tab_quarz_task, bool>> where)
        {
            return await _quarzEFContext.tab_quarz_task.Where(where).AsNoTracking().ToListAsync();
        }`

**Comment by l2999019** [comment]
可以详细的描述一下重现步骤么? 贴一下starup注入的代码..  我这边暂时无法重现

**Comment by xiaotangzi** [comment]
您好 ，我新建了个web项目，引入GZY.Quartz.MUI包，在startup里添加需要的配置，**调试**启动项目后在地址栏后面跟quartzui，页面也可以正常加载，功能也可以正常使用，接下来注意了，我在新建了一条任务，再把调试关了，**重新调试**启动就出现了这个错误。

我用你的源码去调试，发现应该是EFContext上下文注册服务的时候有问题，只要是有关于操作数据库crud的时候都会出问题。
总总是这类错误：

Invalid attempt to read when no data is present.

Invalid attempt to call IsDBNull when reader is closed

There is already an open DataReader associated with this Connection which must be closed 

然后我把你这个类，**EFQuartzService** 里的异步方法都改成同步就可以了。

这应该是一个异步的问题。但具体为什么这样，我不是很清楚。

**Comment by jishufangui** [comment]
IQuartzHandle中的InitJobs 应该为Task类型

**Comment by wanyong117** [comment]
> @xiaotangzi 用的是什么数据库呢? 最新的版本采用了本地化的存储,应该不会有问题了.

本地化存储是正常的。换成Mssql数据库方式就不行，会抛出这个异常：Invalid attempt to call ReadAsync when reader is closed。

**Comment by l2999019** [comment]
> > @xiaotangzi 用的是什么数据库呢? 最新的版本采用了本地化的存储,应该不会有问题了.
> 
> 本地化存储是正常的。换成Mssql数据库方式就不行，会抛出这个异常：Invalid attempt to call ReadAsync when reader is closed。

我会抽空用MSSQL调试一下看看

**Comment by ganjubing** [comment]
链接mysql没有问题，我换成了mssql后，也会报Invalid attempt to call ReadAsync when reader is closed.错误，但是表已经创建，求解决方案

**Comment by l2999019** [comment]
> 链接mysql没有问题，我换成了mssql后，也会报Invalid attempt to call ReadAsync when reader is closed.错误，但是表已经创建，求解决方案

我近期在解决这个问题 应该是容器注入形式导致这块有点异常

**Comment by l2999019** [comment]
MYSQL的话 建议使用官方的驱动 不要使用Pomelo的驱动
