### ISSUE TITLE
兄弟，跑起来没有办法控制Job不允许并发的控制

### ISSUE THREAD

**Issue by liupeng5843** [l2999019/GZY.Quartz.MUI#23]
ClassJobs没有加DisAllowConcurrentExecution控制任务并发执行，这个轮子怎么做才能控制不并发

**Comment by SG-009** [comment]
自己加个分布锁

**Comment by SG-009** [comment]
你试试
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/109298325/f99a59f7-a59d-48e6-80db-acabc661c42d)

![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/109298325/c9c79cce-13cb-45a0-bb1d-0e08e658d0ae)
