### ISSUE TITLE
大佬：Value cannot be null. (Parameter 'content')

### ISSUE THREAD

**Issue by zhang1446802857** [l2999019/GZY.Quartz.MUI#24]
大佬。不知道这个是什么问题。我的接口没有参数呀，通过ui创建的任务

**Comment by wozehua** [comment]
建议不要用2.4.0 有这个bug

**Comment by zhang1446802857** [comment]
> 建议不要用2.4.0 有这个bug

辞职了已经

**Comment by wozehua** [comment]
这个包还有个bug就是升级后回报找不到分组

**Comment by zhang1446802857** [comment]
> 这个包还有个bug就是升级后回报找不到分组
不知道，给公司搞了这个。也没说过有问题

**Comment by l2999019** [comment]
这个问题 我关闭了 升级到最新的版本 就好

**Comment by lixuInsist** [comment]
Value cannot be null. (Parameter 'content') 我用的2.6.0，还是会报错

**Comment by windbell2** [comment]
同样也有这个问题

**Comment by windbell2** [comment]
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/5801605/fb8c1cbe-8dd5-46e0-bd93-67c3f39973db)
