### ISSUE TITLE
大佬，数据库版本.net6的感觉跑不起来

### ISSUE THREAD

**Issue by emaoxiongzhang** [l2999019/GZY.Quartz.MUI#25]
`//数据库版本
var optionsBuilder = new DbContextOptionsBuilder<GZY.Quartz.MUI.EFContext.QuarzEFContext>();

var sqlStr = builder.Configuration.GetConnectionString("mysql");

optionsBuilder.UseMySql(sqlStr,new MySqlServerVersion(new Version(5,7,33)));//创建数据库连接
builder.Services.AddQuartzUI(optionsBuilder.Options); //注入UI组件`

引入了 using Pomelo.EntityFrameworkCore;这个包，但是app.userQuartz();报错
`System.MissingMethodException:“Method not found: 'System.Type `

我看了下源码是不是efcore 也需要升级到6版本啊[https://github.com/Innofactor/EfCoreJsonValueConverter/issues/15](url)

**Comment by l2999019** [comment]
有没有详细信息? 我应该是没有引用你说的这个包
