### ISSUE TITLE
优化新功能

### ISSUE THREAD

**Issue by ycbbcy** [l2999019/GZY.Quartz.MUI#27]
希望新建任务的时候可以发射任务的特定属性到任务表述字段，有助于新任务的创建。

**Comment by l2999019** [comment]
...没看懂啥意思  发射任务??

**Comment by ycbbcy** [comment]
> ...没看懂啥意思 发射任务??

说错了，希望接口有一个描述属性，这样在创建任务的时候可以参考该描述或者模版说明来创建参数，（比如该任务需要提供三个参数，分别为Abc）

**Comment by l2999019** [comment]
我记得任务里面有个 任务描述 字段 你可以在这个地方填写你想要填写的信息
