### ISSUE TITLE
能否支持执行记录的消息可以换行，比如支持/r/n或者支持<br />

### ISSUE THREAD

**Issue by smilesxsy** [l2999019/GZY.Quartz.MUI#29]

**Comment by l2999019** [comment]
这个应该可以支持

**Comment by smilesxsy** [comment]
@l2999019 希望版本上能得到支持
在执行记录的消息支持html标签
<el-table-column prop="Msg" label="消息" align="center" :show-overflow-tooltip="true"> 
    <template slot-scope="scope">
        <div v-html="scope.row.Msg"></div>
    </template>
</el-table-column>

**Comment by smilesxsy** [comment]
![Snipaste_2024-06-06_16-23-09](https://github.com/l2999019/GZY.Quartz.MUI/assets/40155072/ae9cc454-5017-47d0-b328-44965b070db2)

**Comment by l2999019** [comment]
我感觉加这个 会不会影响现有排版...
