### ISSUE TITLE
是否支持集群模式

### ISSUE THREAD

**Issue by qh279650038** [l2999019/GZY.Quartz.MUI#30]
大佬请问一下，如何配置才能使其支持集群

**Comment by l2999019** [comment]
...你是要支持什么集群模式?

**Comment by l2999019** [comment]
> > ...你是要支持什么集群模式?
> 
> 比如 将此应用部署到多台服务器上，保证多台服务器中的某个任务 在指定时间 只有其中一台服务器执行（可以是随机的，也可以是根据服务器空闲情况）

那其实我觉得没必要,
如果你想通过集群权重选举的方式去执行某个任务,
反而不应该由定时任务去做这个事情, 
因为定时任务的任务量级很难大到需要集群的,
你反而是需要将自己的业务服务集群化 然后对定时任务提供统一的接口(也许是网关,也许是nginx代理)
由你的代理服务去选举应该由谁来执行后面的逻辑
