### ISSUE TITLE
是否可以配置关闭日志，JobService 是否有异步实现

### ISSUE THREAD

**Issue by ljc1160** [l2999019/GZY.Quartz.MUI#32]
1. 是否可以关闭日志，有时候需要控制台调试，一直在刷
![image](https://github.com/l2999019/GZY.Quartz.MUI/assets/41314183/a67221a2-ba9f-4720-839f-f344c7c01683)

2. JobService 是否有异步实现，现在大多数方法返回都是 Task，如果没有异步实现，无法使用 await，只能通过 .Result 获取结果

**Comment by l2999019** [comment]
1.日志可以通过ASP.NET的配置 不输出info级别的日志, 不过确实也应该加一个全局配置项.感谢建议
2.异步实现在定时任务里面应该是不用的.如果不等待结果 直接返回task 可能当前线程的任务都没执行完 会导致执行乱序 而且结果记录也会不准确
