### ISSUE TITLE
是否可以固定页面表格头部，当任务多的时候，划到最下面再拉到顶部选择操作按钮比较麻烦

### ISSUE THREAD

**Issue by xds135** [l2999019/GZY.Quartz.MUI#34]
我现在15条任务，就操作比较麻烦了，而且万一选错了，还要重新拉到底部，重新选择。或者是否可以增加一个搜索框——搜索任务名称或者分组名称，或者增加创建时间排序，这样的话最新的在上面也还好

**Comment by l2999019** [comment]
接受建议 确实有这个问题
