### ISSUE TITLE
提几个建议

### ISSUE THREAD

**Issue by JasonWangJie** [l2999019/GZY.Quartz.MUI#35]
httpAPI任务时候会导致超时，默认只有十秒，最好设置可在配置文件内配置。
执行记录是否可以倒置这样更方便看，
日志内容可设置保留多久。
其他很好用

**Comment by l2999019** [comment]
1.正在补充这部分内容,下个版本应该会搞
2.打算设置成可排序
3.建议很好打算加个全局参数
