### ISSUE TITLE
net5 efcore 5.0貌似不可用

### ISSUE THREAD

**Issue by pengtao779** [l2999019/GZY.Quartz.MUI#5]
NET5 如果想用数据库方案貌似不行，是否是EFCORE 包只是3.0 没有升级到5.0版本，后期是否会升级。
最后想说开箱即用，很棒，谢谢

**Comment by l2999019** [comment]
肯定会升级的. 我在考虑是否直接升级到6.0版本

**Comment by chukaif** [comment]
> 肯定会升级的. 我在考虑是否直接升级到6.0版本

建议分别提供5.0和6.0版本，版本号可以跟.net版本一致 5.x.x和6.x.x

**Comment by l2999019** [comment]
已升级
