### ISSUE TITLE
打包成单文件时,无法使用dll的方式运行任务,程序集加载会报错!

### ISSUE THREAD

**Issue by JerryLiew** [l2999019/GZY.Quartz.MUI#6]
![image](https://user-images.githubusercontent.com/51161678/167279785-a8e3400e-36b6-4112-9ca5-24a9efbe0af1.png)
![image](https://user-images.githubusercontent.com/51161678/167279790-b1952b34-3339-4044-a378-1d53a722b019.png)
如图,如果打包成singel file 就会出这个问题,dll方式运行任务,找不到指定类型

**Comment by l2999019** [comment]
单文件打包 是不是把你需要注入的类的dll打掉了.. 自动搜索不到 就会这样

**Comment by JerryLiew** [comment]
是这样的, 目前只是扫描dll进行注入,只需要在遍历dll注入的时候把exe 自身程序集里面的类也注入就好了

**Comment by JerryLiew** [comment]
已经解决,等我有空提个pr,你看下是否要合并进去

**Comment by l2999019** [comment]
好的

**Comment by wxlnet** [comment]
目前只支持SQL Server数据库？支持Oracle吗

**Comment by wxlnet** [comment]
![image](https://user-images.githubusercontent.com/65823238/170879805-c0846a64-62e4-4dc3-a359-cec75abbb046.png)
调用API时候这里报错了求解答，谢谢

**Comment by l2999019** [comment]
@wxlnet  支持oracle 需要你自行注入oracle的访问库
