### ISSUE TITLE
引用最新nuget包时报错。

### ISSUE THREAD

**Issue by geekworm** [l2999019/GZY.Quartz.MUI#9]
报错提示：
错误 NU1108 检测到循环。
Quartz -> GZY.Quartz.MUI 1.1.5 -> Quartz (>= 3.3.3).

![image](https://user-images.githubusercontent.com/12904579/188419419-97252b67-3afb-496c-b88b-e02b3bb1b2f5.png)

**Comment by l2999019** [comment]
@geekworm ..我最新的版本才更新到2.0  你这2.1是怎么来的..
